version: "3.8"

services:
  vortex:
    build: .
    ports:
      - "80:3000"
    links:
      - "rethink:rethink"
      - "redis:redis"
  rethink:
    image: rethinkdb:latest
  redis:
    image: redis:latest
