version: "3.8"

volumes:
  mongo-data:


services:
  vortex:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - "mongo:mongo"
      - "redis:redis"
    command: [ "/bin/bash", "-c", "npm -g install nodemon; npm run dev & nodemon index.js" ]
    volumes:
      - ./:/usr/src/app
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/etc/mongo
  mongoku:
    image: huggingface/mongoku:latest
    ports:
      - "127.0.0.1:3100:3100"
    environment:
      - MONGOKU_DEFAULT_HOST=mongodb://mongo:27017
  redis:
    image: redis:latest
