version: "3.8"

volumes:
  postgres-data:


services:
  vortex:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - "postgres:postgres"
      - "redis:redis"
    command: [ "npm", "test" ]
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=vortex
  redis:
    image: redis:latest
