version: "3.8"

volumes:
  mongo-data:


services:
  vortex:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - "mongo:mongo"
      - "redis:redis"
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/etc/mongo
  redis:
    image: redis:latest
